name: Build and Push Docker Image


on:
  push:
    branches:
      - qa
      - pps-master
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: qa
        type: choice
        options:
          - qa
          - pps-master

run-name: "Build #${{ github.run_number }} [${{ github.ref_name }}] - ${{ github.event.head_commit.message || 'Manual Run' }}"

env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  REGION: ${{ secrets.REGION }}
  
jobs:
  build-and-push-ecr:
    # For production branch, use production runner, otherwise use dev runner
    runs-on: ${{ (github.event.inputs.branch || github.ref_name) == 'pps-master' && fromJson('["self-hosted","production"]') || fromJson('["self-hosted","dev"]') }}
  
    # Set environment for deployment job based on branch
    environment: ${{ 
      (github.event.inputs.branch || github.ref_name) == 'pps-master' && 'production' ||
      (github.event.inputs.branch || github.ref_name) == 'qa' && 'dev' }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
                  ref: ${{ github.event.inputs.branch || github.ref_name }}
                  
      - name: Set Environment Variables
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch || github.ref_name }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "${{ vars.ENV_FILE }}" > .env
          echo "${{ vars.ENV }}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_REGISTRY


      - name: Build Docker Image
        run: |
            docker build -t $ECR_REGISTRY/$IMAGE_NAME-$ENV:$IMAGE_TAG .



            

      - name: Push Docker Image to ECR
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME-$ENV:$IMAGE_TAG

      - name: Remove Built Docker Image
        if: always()
        run: |
          docker rmi $ECR_REGISTRY/$IMAGE_NAME-$ENV:$IMAGE_TAG || true

      - name: Cleanup Docker
        if: always() && vars.CLEANUP_DOCKER == 'true'
        run: |
          docker system prune -af --volumes
          
      - name: Cleanup workspace
        if: always()
        run: |
          find "$GITHUB_WORKSPACE" -mindepth 1 -maxdepth 1 -exec rm -rf {} +


  trigger-deploy:
    needs: build-and-push-ecr
    if: (github.event.inputs.branch || github.ref_name) != 'pps-master'
    uses: ./.github/workflows/deploy.yml
    with:
      branch: ${{ github.event.inputs.branch || github.ref_name }}
      image_tag: ${{ github.run_number }}
    secrets: inherit
